### ISSUE TITLE
Firefox: Log text is dark text on dark background

### ISSUE THREAD

**Issue by amezick** [ForkPoint/dwithease#12]
I have Firefox set to use system colors.
![image](https://user-images.githubusercontent.com/870916/173366853-b6885116-ba9c-45b0-b849-bf3852dbf92f.png)

Windows 11 to dark mode
![image](https://user-images.githubusercontent.com/870916/173366979-756bddc1-5343-41c1-a196-bccccc77df3d.png)

The jobs log (among others) is dark text on dark background and completely unreadable.
![image](https://user-images.githubusercontent.com/870916/173367200-64022ec4-15cd-4d19-a4bc-2cb7f5a2c795.png)

The darkmode in your settings does not change this.
![image](https://user-images.githubusercontent.com/870916/173367427-40b1ce77-19f7-4026-b817-3e24a4e5b17d.png)

**Comment by amezick** [comment]
I am using version 3.3.4.

**Comment by amezick** [comment]
I believe I see this resolved in 3.6.0

**Comment by danieldudin** [comment]
Hi, @amezick this is indeed fixed in version 3.6.0, thanks for your report and fix confirmation! Cheers!
