### ISSUE TITLE
Notifcation for common tasks completed

### ISSUE THREAD

**Issue by maxjf1** [ForkPoint/dwithease#14]
Great extension! 

This is an feature idea if possible.

Add push notifications for completion of common tasks, such as search indexing, importing catalog etc.

normally we need to manually push refresh now and then. Would be great to have this feature baked on the project.

**possible solution:** When detecting an action such as search indexing, register the action listening (eg: local storage), and periodically (5 in 5 seconds) check the task completion (by reloading the tab or fetching). after detection, notify user and remove listener.

**Comment by danieldudin** [comment]
Hello @maxjf1 ! Thank you for your suggestions, we will consider improving the visibility of when DWithEase actions are still in progress/or complete! 
We currently have some "monitoring" logic in place for the BM Toolbar actions, but it seems like it's not fully working every time.
