### ISSUE TITLE
Auto-fill Not Working

### ISSUE THREAD

**Issue by yetisenkadir** [ForkPoint/dwithease#15]
Hello,

It no longer auto-fills the email and password fields.

It enters the password for email input.

![2024-02-07_10h52_01](https://github.com/ForkPoint/dwithease/assets/105480491/606cff49-38b4-4f39-90b2-8e16c01b1189)

would you investigate this issue?

thanks

**Comment by alimonculOSF** [comment]
Same for me

**Comment by kalinstanchev** [comment]
There was an update from SF yesterday and that broke the auto fill functionality. I hope they are investigating...

**Comment by k2kirov** [comment]
Hi all, we have submitted a fix on the Dev channel here https://chrome.google.com/webstore/detail/demandware-with-ease-dev/dgeefjobfkigeddklecnmjpfdiadodnd?hl=en we will publish a fix to the Main channel tomorrow :)

**Comment by alpenite-mattias** [comment]
Hi all, is there a chance to fix the new behavior in Firefox?

**Comment by danieldudin** [comment]
Hello! Thanks all for your quick reports! The issue is now fixed in version 3.11.1, we have plans to release it also on Firefox soon! Stay tuned! Cheers!
