### ISSUE TITLE
extension popup's location is unvisible when window is located to left

### ISSUE THREAD

**Issue by 75asa** [ForkPoint/dwithease#6]
like this
![image](https://user-images.githubusercontent.com/35181442/99019993-f75d1600-25a0-11eb-913c-e35cafecbe93.png)

no problem when it located right
![image](https://user-images.githubusercontent.com/35181442/99020068-1bb8f280-25a1-11eb-87fa-d14797b9cb4c.png)

**Comment by danieldudin** [comment]
This is browser behavior so there is not much that we can do here. We need to define a fixed width for the popup, and it can't be made responsive.
