### ISSUE TITLE
Ability to set default site

### ISSUE THREAD

**Issue by shaneoreilly** [ForkPoint/dwithease#7]
Hi there,

Is there any way to set a default site within the Sandbox Configurations?

Thanks!
Shane

**Comment by danieldudin** [comment]
Hi, @oreillygshane There is an official setting provided by Salesforce where you can set a preferred site to be selected after you log in to an environment. You can find it by clicking on your name in the top right corner (in Business Manager), after you access your profile the setting is found under Preferences -> Preferred Site After Login. 
I hope that helps. Cheers!

**Comment by shaneoreilly** [comment]
Amazing, thanks!!
