### ISSUE TITLE
WebDAV - Unable to switch to default view from tree view in content folders

### ISSUE THREAD

**Issue by eyenigunsfcc** [ForkPoint/dwithease#8]
Within Business Manager > Administration > Site Development > Development Setup > Content Folders

Folder URL generated by 'Copy WebDAV URL' takes user to Tree View of empty WebDAV interface, user is unable to switch to default view, upload or open files, or view contents of webDAV location. 

Tested on multiple sandboxes with correct URLs and non empty content folders on latest release of DWithEase, clean install of latest release seems to work until user switches to Tree View. This triggers the above issue to occur again without any way to revert without uninstalling, reinstalling, and avoiding Tree View altogether

images show BM SharedLibrary / Default path and DWithEase open to same path on same instance

![dw_issue_1](https://user-images.githubusercontent.com/79173734/140567399-fdb92182-c12c-4ae7-9907-ca2f213d0d22.png)
![dw_issue_2](https://user-images.githubusercontent.com/79173734/140567406-a9b24b7c-78a2-4e78-a950-69aa17306f76.png)
![dw_issue_3](https://user-images.githubusercontent.com/79173734/140567409-afabce99-46e1-4a58-ba68-1415014b506a.png)
![Screen Shot 2021-11-05 at 3 25 41 PM](https://user-images.githubusercontent.com/79173734/140567426-f2af5443-ca28-46a6-a1cb-ea0a84040034.png)
![Screen Shot 2021-11-05 at 3 25 22 PM](https://user-images.githubusercontent.com/79173734/140567433-c72f0cdc-0fa0-4d70-8b97-99f9c8548b00.png)

**Comment by danieldudin** [comment]
A solution has been implemented in some of the old versions, all WebDav directories should now be loading, if Tree view is not available for them, it should fall back to WebDav v1 (original view), not blocking the User in any way from using the directory. Marking as resolved please let us know if you still face issues. Cheers!
