### ISSUE TITLE
Firefox extension  no longer available 

### ISSUE THREAD

**Issue by Elythingol** [ForkPoint/dwithease#9]
Hi, looks like firefox extension was removed from store: https://addons.mozilla.org/en-US/firefox/addon/dwithease/

**Comment by ExposedCat** [comment]
And no source code to fix it yourself. Why extension it proprietary at all 🤔

**Comment by pedrozebra** [comment]
Hi, we are not yet able to download the firefox extension, do you have any ideas?
Thanks

**Comment by b-douglas** [comment]
I assume because it is broken.

Once salesforce has moved to Lightning UI , it broke for me and doesn't work anymore.

It still works on Chrome though.

**Comment by ExposedCat** [comment]
Issue was fixed today, now DWithEase works fine in Firefox

**Comment by b-douglas** [comment]
Awesome!

**Comment by danieldudin** [comment]
DWithEase is now available on Firefox.
